language: php
php:
- 5.4
before_script:
- composer install
script:
- mkdir -p build/logs
- phpunit --testsuite unit --coverage-clover build/logs/clover.xml
- phpunit --testsuite travis
- phpunit --testsuite integration
after_script:
- php vendor/bin/coveralls -v
- vendor/bin/test-reporter
env:
  global:
  - secure: XTDL4WxfsGGVyCPAhp2sWsLLrWufUTDPJ0nwiUpZEmd14D/2D/lS5WsXPJwe3Cend0EHn5IgpmeepDVbSpwKbVINKJOupw1LOB3dVDZ8+pO86EVSFrTcPIfJjcb4DXPD6Xf6NlPzkMayMwi8De9JHZaNgipYBdHYJh/KjSwswu0=
  - secure: tBazD2ZCgj9gAOvxYz6mp/ojYeU4vnvZRhgehUAeg3Qc9U856tmzed8F20EEWI5yAHUWOlHAlG+6JIZ3A8eIcVrxx3HxdeDTBZChKJelubKqyJ8BqoGeoE7qNoYiUDjyu0ikgQxI/hkNmbzb83pkavYRjipXcJTtt5XlO9HHfa0=
matrix:
  fast_finish: true
addons:
  code_climate:
    repo_token: 227b762d94c244cab0557b821f2605a9abfafab1343adf4b1adaa164b46f5ca0