language: php
php:
- 5.4
before_script:
- composer install
script:
- phpunit --testsuite unit
- phpunit --testsuite integration
env:
  global:
  - secure: QPMq33ut7lOWvwQi6+OpSqDlZRCrkkLqQ/3+zfoakCii+RhZwuy7+Ox5IkEgbk+FNQuiE6dK7IcRyFbOGMEwe0+hrtEcHAfJUXVnJeXMMFXI6/en3OlL7aBBUyY5TacUdhAcEJti2RWDOJwatwfn7vUHfs+WzmQ4JsgHjjX5dco=
  - secure: Ce+wNBUKKpk4jxwadCcUaeFgHNGt+rNO6olOzpqaDJ5qyz+N17w0UB475yWCQS/3R+s+avk9xHl9K47ExK87D0/XStIx3OesZsE5y8B+hv2aAoacRVcFrgHgZSZndWb+v6BgLORraNmJs//bDfIGqFYu4CFljlD6s4Hv+Rwr3/I=
